name: "BigMLer tests 18"

on:
  pull_request:
    paths-ignore:
      - 'docs/**'
      - '*.rst'
  workflow_dispatch:

jobs:
  tests-18:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: [3.10]
    env:
        BIGML_USERNAME: ${{ secrets.BIGML_USERNAME }}
        BIGML_API_KEY: ${{ secrets.BIGML_API_KEY }}
        BIGML_ORGANIZATION: ${{ secrets.BIGML_ORGANIZATION }}
        BIGML_EXTERNAL_CONN_HOST: ${{ secrets.BIGML_EXTERNAL_CONN_HOST }}
        BIGML_EXTERNAL_CONN_PORT: ${{ secrets.BIGML_EXTERNAL_CONN_PORT }}
        BIGML_EXTERNAL_CONN_DB: ${{ secrets.BIGML_EXTERNAL_CONN_DB }}
        BIGML_EXTERNAL_CONN_USER: ${{ secrets.BIGML_EXTERNAL_CONN_USER }}
        BIGML_EXTERNAL_CONN_PWD: ${{ secrets.BIGML_EXTERNAL_CONN_PWD }}
        BIGML_DELTA: 5
    steps:
    - name: Install packages
      uses: actions/checkout@v3
    - run: |
        pip install bigml[full]>=9.1.3
        pip install .[full]

    - name: Run tests *18*
      run: |
        pip3 install pytest
        export TESTS=$(for t in "18" "19" "20" "21" "22"; do ls bigmler/tests/*$t*.py;done|paste -sd " ")
        echo $TESTS
        pytest -s $TESTS
