name: "BigMLer tests 28"

on:
  pull_request:
    paths-ignore:
      - 'docs/**'
  workflow_dispatch:

jobs:
  tests-28:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: [3.8]
    env:
        BIGML_USERNAME: ${{ secrets.BIGML_USERNAME }}
        BIGML_API_KEY: ${{ secrets.BIGML_API_KEY }}
        BIGML_ORGANIZATION: ${{ secrets.BIGML_ORGANIZATION }}
        BIGML_EXTERNAL_CONN_HOST: ${{ secrets.BIGML_EXTERNAL_CONN_HOST }}
        BIGML_EXTERNAL_CONN_PORT: ${{ secrets.BIGML_EXTERNAL_CONN_PORT }}
        BIGML_EXTERNAL_CONN_DB: ${{ secrets.BIGML_EXTERNAL_CONN_DB }}
        BIGML_EXTERNAL_CONN_USER: ${{ secrets.BIGML_EXTERNAL_CONN_USER }}
        BIGML_EXTERNAL_CONN_PWD: ${{ secrets.BIGML_EXTERNAL_CONN_PWD }}
        BIGML_DELTA: 5
    steps:
    - name: Install packages
      uses: actions/checkout@v2
    - run: |
        pip install .[full]

    - name: Run tests *28 29 30 31 32 33 41 42*
      run: |
        export TESTS=$(for t in "28" "29" "30" "31" "32" "33" "41" "42"; do ls bigmler/tests/*$t*.py;done|paste -sd ",")
        echo $TESTS
        python setup.py nosetests --nocapture --tests=$TESTS
